### PR TITLE
Sort objects according to the supplied schema

### LINKED ISSUE #871: Composer repository objects are sorted differently when in an array or an object
When using `composer normalize` version `2.30.2`, the action taken on the contents of the `repositories` property is not consistent.

#### Steps required to reproduce the problem

1. Given the following `composer.json` (where 'repositories' is an array):

   ```json
   {
     "repositories": [
       {
         "url": "http://packages.example.com",
         "only": [ "example/*" ],
         "type": "composer"
       }
     ]
   }
   ```

1.  `composer normalize` results in:

   ```json
   {
     "repositories": [
       {
         "type": "composer",
         "url": "http://packages.example.com",
         "only": [
           "example/*"
         ]
       }
     ]
   }
   ```

However...

1. Given the following `composer.json` (where 'repositories' is an object):

   ```json
   {
     "repositories": {
       "example": {
         "url": "http://packages.example.com",
         "only": [ "example/*" ],
         "type": "composer"
       }
     }
   }
   ```

1.  `composer normalize` results in:

   ```json
   {
     "repositories": {
       "example": {
         "only": [
           "example/*"
         ],
         "type": "composer",
         "url": "http://packages.example.com"
       }
     }
   }
   ```

#### Expected Result

- Key order is consistent for repository objects.

#### Actual Result

- Key order is inconsistent.
  - Arrays are sorted: `type`, `url`, `only`
  - Objects are sorted: `only`, `type`, `url`

### PR DESCRIPTION
**Pull request by fredden**
This pull request

- [x] Ensures objects are always sorted according to their schema, unless specifically configured otherwise

Fixes #871

I'm unsure if the changes in the last commit (9d699869ca7efde6bf0b4d9ca3931632ef2a8f9f) are desired, or if we should change the code to preserve that behaviour.

### CODE REVIEW

File: src/SchemaNormalizer.php [hunk 1]
```diff
@@ -230,6 +230,16 @@ private function normalizeObject(
...
 
+        /**
+         * @see https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties
+         */
+        if (
+            \property_exists($schema, 'additionalProperties')
+            && \is_object($schema->additionalProperties)
+        ) {
+            $valueSchema = $schema->additionalProperties;
+        }
```
Comment (localheinz) [inline src/SchemaNormalizer.php:241]: @fredden 

I think this solves the problem better, what do you think?

**Review by localheinz — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you very much, @fredden!

File: src/SchemaNormalizer.php (hunk 1 above)
Comment (fredden) [reply src/SchemaNormalizer.php:241]: Yes, this looks like a much cleaner solution. Thanks for working through this. :+1:
